apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  volumes:
  - name: mongodb-data-2           
    persistentVolumeClaim:
      claimName: mongodb-pvc-aws-ebs
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data-2        
      mountPath: /data/db        
    ports:
    - containerPort: 27017
      protocol: TCP   