---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-app2
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-app2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-app2
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <filesystem-id>::<accesspoint-id>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-app2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-app2
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app2
spec:
  containers:
  - name: app2
    image: busybox 
    command: ["/bin/sh"] 
    args: ["-c", "while true; do echo $(date -u) app2 >> /data/out2.txt; sleep 60; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim-app2
