apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-efs
spec:
  storageClassName: efs-sc
  resources:
    requests:                    
      storage: 100Mi                        
  accessModes:                              
  - ReadWriteOnce    