apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-aws-ebs
spec:
  storageClassName: test-gp2
  resources:
    requests:                    
      storage: 100Mi                        
  accessModes:                              
  - ReadWriteOnce  